// <auto-generated />
using System;
using BlockchainMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlockchainMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(BlockchainDbContext))]
    partial class BlockchainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("BlockchainMonitor.Domain.Entities.BlockchainData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BaseFee")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HighFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("HighGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("HighPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<string>("LastForkHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastForkHeight")
                        .HasColumnType("bigint");

                    b.Property<string>("LatestUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LowFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("LowGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("LowPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumFeePerKb")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumGasPrice")
                        .HasColumnType("bigint");

                    b.Property<long?>("MediumPriorityFee")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PeerCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousUrl")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Name");

                    b.ToTable("BlockchainData");
                });
#pragma warning restore 612, 618
        }
    }
}
